name: Deploy Ecommerce Fullstack App on EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Step 2: Debug - list files in repo
      - name: List repo files
        run: ls -la

      # Step 3: Copy files to EC2
      - name: Copy repo to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.EC2_HOST }}      # ✅ CHANGED: secrets → vars
          username: ubuntu
          key: ${{ vars.EC2_SSH_KEY }}    # ✅ CHANGED: secrets → vars
          port: 22
          source: "."
          target: /home/ubuntu/ecommercefullstack

      # Step 4: Deploy on EC2
      - name: Deploy on EC2 with Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.EC2_HOST }}      # ✅ CHANGED: secrets → vars
          username: ubuntu
          key: ${{ vars.EC2_SSH_KEY }}    # ✅ CHANGED: secrets → vars
          port: 22
          script_stop: true
          script: |
            cd /home/ubuntu/ecommercefullstack
            
            # Install Docker Compose (not just plugin)
            if ! command -v docker-compose &> /dev/null; then
              sudo apt-get update -y
              sudo apt-get install -y docker-compose
            fi

            # Stop and start with docker-compose
            sudo docker-compose down
            sudo docker-compose up -d --build
