name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy repo to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.EC2_HOST }}
          username: ubuntu
          key: ${{ vars.EC2_SSH_KEY }}
          port: 22
          source: "."
          target: /home/ubuntu/ecommercefullstack

      - name: Deploy on EC2 with Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.EC2_HOST }}
          username: ubuntu
          key: ${{ vars.EC2_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            cd /home/ubuntu/ecommercefullstack
            
            # Install Docker Compose if needed
            if ! command -v docker-compose &> /dev/null; then
              sudo apt-get update -y
              sudo apt-get install -y docker-compose
            fi

            # Deploy with Docker Compose
            sudo docker-compose down
            sudo docker-compose up -d --build
