services:
  db:
    image: mysql:8.0
    container_name: cineva-db
    environment:
      MYSQL_ROOT_PASSWORD: Bhargavi@2005
      MYSQL_DATABASE: video
    ports:
      - "3308:3306"

  backend:
    build: ./CinevaBackend
    container_name: cineva-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/video?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Bhargavi@2005
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8082:8081"

  frontend:
    build: .  # ← CHANGED: ./docker-frontend → .
    container_name: cineva-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
