name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        container_name: cineva-db
        env:
          MYSQL_ROOT_PASSWORD: Bhargavi@2005
          MYSQL_DATABASE: video
        ports:
          - 3308:3306

      backend:
        build: ./CinevaBackend
        container_name: cineva-backend
        depends_on:
          db:
            condition: service_healthy
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/video?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: Bhargavi@2005
          SPRING_JPA_HIBERNATE_DDL_AUTO: update
        ports:
          - 8082:8081

      frontend:
        build: . 
        container_name: cineva-frontend
        depends_on:
          - backend
        ports:
          - 3000:80

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add other steps such as build, test or deploy here
